version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserver
    environment:
      SA_PASSWORD: "salaM123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mssql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=TestDb;User Id=sa;Password=salaM123@;"
    ports:
      - "5000:8080"
    networks:
      - appnet

volumes:
  mssqldata:

networks:
  appnet:
